import "./globals.css"
import type { Metadata } from "next"
import { VT323 } from "next/font/google"
import { Navbar } from "@/components"
import { ContextProvider } from "@/context"

const VT323Font = VT323({
	weight: "400",
	style: "normal",
	subsets: ["latin-ext"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className="dark">
			<body className={VT323Font.className}>
				<ContextProvider>
					<Navbar />
					{children}
				</ContextProvider>
			</body>
		</html>
	)
}
